name: XChange CI
on:
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
        env:
          CI: true
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build --if-present
      - name: Upload app build
        uses: actions/upload-artifact@v1
        with:
          name: xchange-build
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download app build
        uses: actions/download-artifact@v1
        with:
          name: xchange-build
      - name: Print final result
        shell: bash
        run: |
          ls dist
      # - name: Deploy to netlify
      #   uses: netlify/actions/cli@master
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   with:
      #     args: deploy --dir=dist --prod
      #     secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
